# -*- coding: utf-8 -*-
"""client1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Sh3ymHPf_a-4p09_ezsEW2HebvXWLPWE
"""

import socket

# Create a socket object
client_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

# Get the local machine name
host = socket.gethostname()

# Reserve a port for your service.
port = 12345

# Connect to the server
client_socket.connect((host, port))

# Define the cards for this client
cards = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

# Play 13 rounds of the game
for i in range(13):
    # Receive the server card
    server_card = int(client_socket.recv(1024).decode())
    print("Server card:", server_card)
    # Send a card to the server
    card = cards.pop(0)
    client_socket.send(str(card).encode())
    # Receive the result of the round
    result = eval(client_socket.recv(1024).decode())
    print("Round result:", result)

# Close the connection
client_socket.close()